# Generated by Django 6.0.1 on 2026-08-11 23:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0002_habito_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='habito',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habito',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='habito',
            name='tipo',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], default='positivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='habito',
            name='dias',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CumplimientoHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('completado', models.BooleanField(default=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='habitos.habito')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('habito', 'fecha')},
            },
        ),
    ]
